In [352]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/stroke-prediction-dataset/healthcare-dataset-stroke-data.csv

In [353]:
stroke_data = pd.read_csv('/kaggle/input/stroke-prediction-dataset/healthcare-dataset-stroke-data.csv')

In [354]:
stroke_data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [355]:
stroke_data.shape

(5110, 12)

In [356]:
stroke_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [357]:
stroke_data.duplicated().sum()

0

In [358]:
stroke_data['stroke'].value_counts()

0    4861
1     249
Name: stroke, dtype: int64

----> Data seems to be imbalanced

In [359]:
stroke_data['work_type'].value_counts()

Private          2925
Self-employed     819
children          687
Govt_job          657
Never_worked       22
Name: work_type, dtype: int64

In [360]:
stroke_data['gender'].value_counts()

Female    2994
Male      2115
Other        1
Name: gender, dtype: int64

In [361]:
stroke_data['ever_married'].value_counts()

Yes    3353
No     1757
Name: ever_married, dtype: int64

In [362]:
stroke_data['smoking_status'].value_counts()

never smoked       1892
Unknown            1544
formerly smoked     885
smokes              789
Name: smoking_status, dtype: int64

In [363]:
stroke_data['Residence_type'].value_counts()

Urban    2596
Rural    2514
Name: Residence_type, dtype: int64

### Dropping the first 2 columns as its not required

In [364]:
stroke_data.drop(columns=['id','gender'],inplace=True)

In [365]:
stroke_data.head()

,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

### Checking for columns that is useful or not

In [366]:
stroke_data=pd.get_dummies(stroke_data, columns=['ever_married','work_type','Residence_type', 'smoking_status'])

In [367]:
stroke_data

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.6,1,0,1,0,0,1,0,0,0,1,0,1,0,0
1,61.0,0,0,202.21,NaN,1,0,1,0,0,0,1,0,1,0,0,0,1,0
2,80.0,0,1,105.92,32.5,1,0,1,0,0,1,0,0,1,0,0,0,1,0
3,49.0,0,0,171.23,34.4,1,0,1,0,0,1,0,0,0,1,0,0,0,1
4,79.0,1,0,174.12,24.0,1,0,1,0,0,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,80.0,1,0,83.75,NaN,0,0,1,0,0,1,0,0,0,1,0,0,1,0
5106,81.0,0,0,125.20,40.0,0,0,1,0,0,0,1,0,0,1,0,0,1,0
5107,35.0,0,0,82.99,30.6,0,0,1,0,0,0,1,0,1,0,0,0,1,0
5108,51.0,0,0,166.29,25.6,0,0,1,0,0,1,0,0,1,0,0,1,0,0
5109,44.0,0,0,85.28,26.2,0,0,1,1,0,0,0,0,0,1,1,0,0,0

In [368]:
stroke_data= stroke_data.dropna()

### Scaling the values

In [369]:
X = stroke_data.drop(columns=['stroke'])
y = stroke_data['stroke']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2, random_state=2)

In [370]:
X

,age,hypertension,heart_disease,avg_glucose_level,bmi,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,67.0,0,1,228.69,36.6,0,1,0,0,1,0,0,0,1,0,1,0,0
2,80.0,0,1,105.92,32.5,0,1,0,0,1,0,0,1,0,0,0,1,0
3,49.0,0,0,171.23,34.4,0,1,0,0,1,0,0,0,1,0,0,0,1
4,79.0,1,0,174.12,24.0,0,1,0,0,0,1,0,1,0,0,0,1,0
5,81.0,0,0,186.21,29.0,0,1,0,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5104,13.0,0,0,103.08,18.6,1,0,0,0,0,0,1,1,0,1,0,0,0
5106,81.0,0,0,125.20,40.0,0,1,0,0,0,1,0,0,1,0,0,1,0
5107,35.0,0,0,82.99,30.6,0,1,0,0,0,1,0,1,0,0,0,1,0
5108,51.0,0,0,166.29,25.6,0,1,0,0,1,0,0,1,0,0,1,0,0
5109,44.0,0,0,85.28,26.2,0,1,1,0,0,0,0,0,1,1,0,0,0

In [371]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3927, 18), (982, 18), (3927,), (982,))

In [372]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [373]:
X_train_scaled

array([[ 0.40528952, -0.31768718, -0.23042861, ...,  2.20679749,
        -0.77139139, -0.42132083],
       [ 0.22724919, -0.31768718, -0.23042861, ..., -0.45314534,
         1.29635878, -0.42132083],
       [-0.17334155, -0.31768718, -0.23042861, ..., -0.45314534,
         1.29635878, -0.42132083],
       ...,
       [-0.39589196, -0.31768718, -0.23042861, ..., -0.45314534,
        -0.77139139, -0.42132083],
       [-1.41962386, -0.31768718, -0.23042861, ..., -0.45314534,
        -0.77139139, -0.42132083],
       [ 0.22724919, -0.31768718, -0.23042861, ..., -0.45314534,
         1.29635878, -0.42132083]])

In [374]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [375]:
model = Sequential()

model.add(Dense(3,activation='sigmoid',input_dim =18))
model.add(Dense(1,activation='sigmoid'))

In [376]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_30 (Dense)             (None, 3)                 57
_________________________________________________________________
dense_31 (Dense)             (None, 1)                 4
=================================================================
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________

In [377]:
model.compile(loss='binary_crossentropy', optimizer ='Adam')

In [378]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
123/123 [==============================] - 0s 1ms/step - loss: 0.6239
Epoch 2/10
123/123 [==============================] - 0s 1ms/step - loss: 0.5066
Epoch 3/10
123/123 [==============================] - 0s 1ms/step - loss: 0.4150
Epoch 4/10
123/123 [==============================] - 0s 1ms/step - loss: 0.3447
Epoch 5/10
123/123 [==============================] - 0s 1ms/step - loss: 0.2924
Epoch 6/10
123/123 [==============================] - 0s 1ms/step - loss: 0.2541
Epoch 7/10
123/123 [==============================] - 0s 1ms/step - loss: 0.2262
Epoch 8/10
123/123 [==============================] - 0s 1ms/step - loss: 0.2059
Epoch 9/10
123/123 [==============================] - 0s 1ms/step - loss: 0.1911
Epoch 10/10
123/123 [==============================] - 0s 1ms/step - loss: 0.1804

Checking weights and biases

In [379]:
model.layers[1].get_weights()

[array([[-0.419244 ],
        [-0.7690628],
        [-1.180075 ]], dtype=float32),
 array([-0.71785086], dtype=float32)]

### Prediction

In [380]:
y_log = model.predict(X_test_scaled)

In [381]:
y_pred = np.where(y_log>0.5, 1,0)

In [382]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9572301425661914

In [383]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(['loss'])